### ISSUE TITLE
Create a retry loop while querying index

### ISSUE THREAD

**Issue by smadha** [memex-explorer/GeoParser#51]
https://github.com/MBoustani/GeoParser/blob/master/geoparser_app/views.py#L261

**Comment by smadha** [comment]
Error trace:

```
Traceback (most recent call last):                                                                                                                                                                          
  File "/geoparser_app/views.py", line 286, in query_crawled_index                                                                                     
    r = requests.get(url, headers=headers, auth=HTTPBasicAuth(username, passwd))                                                                                                                            
  File "/conda/bin/lib/python2.7/site-packages/requests/api.py", line 55, in get                                                                                             
    return request('get', url, **kwargs)                                                                                                                                                                    
  File "/conda/bin/lib/python2.7/site-packages/requests/api.py", line 44, in request                                                                                         
    return session.request(method=method, url=url, **kwargs)                                                                                                                                                
  File "/conda/bin/lib/python2.7/site-packages/requests/sessions.py", line 456, in request                                                                                   
    resp = self.send(prep, **send_kwargs)                                                                                                                                                                   
  File "/conda/bin/lib/python2.7/site-packages/requests/sessions.py", line 596, in send                                                                                      
    r.content                                                                                                                                                                                               
  File "/conda/bin/lib/python2.7/site-packages/requests/models.py", line 694, in content                                                                                     
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()                                                                                                                          
  File "/conda/bin/lib/python2.7/site-packages/requests/models.py", line 630, in generate                                                                                    
    raise ChunkedEncodingError(e)                                                                                                                                                                           
ChunkedEncodingError: IncompleteRead(4122 bytes read, 2020 more expected)                                                                                                                                   

IncompleteRead(4122 bytes read, 2020 more expected)    
```
